### ISSUE TITLE
ValueError: cannot reshape array of size 563 into shape (101,101)

### ISSUE THREAD

**Issue by zxshi** [ybabakhin/kaggle_salt_bes_phalanx#3]
when I run `python3 precisioncv.py \
--model res34v5 \
--fine_size 101 \
--pad_left 13 \
--pad_right 14 \
--batch_size 32 \
--cuda True \
--fold 0 \
--save_weight weights/ \
--start_snap 0 \
--end_snap 3 \`
I got this error:
`Traceback (most recent call last):
  File "precisioncv.py", line 111, in <module>
    pred_null = np.array(pred_null).reshape(-1, args.fine_size, args.fine_size)
ValueError: cannot reshape array of size 563 into shape (101,101)`
I output the shape of `np.array(pred_null)` and get `pred_null shape:  (563,)`

**Comment by ybabakhin** [comment]
There is a strange behavior of `np.array(list)` when not all the numpy arrays in the list are of the same shape. You've encountered it, because you've changed `batch_size` to 32. Consequently, overall number of test images (18,000) is not divisible by 32.
I've fixed it using `np.concatenate`: https://github.com/ybabakhin/kaggle_salt_bes_phalanx/commit/caf0c3f91f4c4ca541ae3c3e71b09e5285e5aaba

**Comment by zxshi** [comment]
OK, it can work well.
Thank you very much!
